### PR TITLE
Initial Push

### PR DESCRIPTION
**Pull request by tobbenb**

### CODE REVIEW

**Review by alex-phillips — CHANGES_REQUESTED** [review]

**Comment by Roxedus** [comment]
What about the donate file?

**Comment by tobbenb** [comment]
> What about the donate file?

Isn't it there? It was earlier.

**Comment by Roxedus** [comment]
> Isn't it there? It was earlier.

I do not see a root/donate.txt file, no

**Comment by tobbenb** [comment]
> > Isn't it there? It was earlier.
> 
> I do not see a root/donate.txt file, no

See above

**Review by Roxedus — APPROVED** [review]

**Review by j0nnymoe — APPROVED** [review]

**Pull request merged**
