### PR TITLE
display image version and support link

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by thelamer** [comment]
This likely needs to be a patch file or something else so it will fail if it doesn't work. Just in general it will be an easy thing to mess with and sidestep. The best methodology would likely be just including notes in the readme or having a nag screen landing that runs once and is dismissed.

**Comment by aptalca** [comment]
Upstream wanted to make it clear that they wouldn't be providing support to users using our image. However, their attempt is without a solution. My motivation here is to provide that solution by telling them where to go to get support.

I specifically didn't want to use a patch file because I didn't want the builds to fail in case the sed failed. If the upstream changes things and the sed never occurs, it's not that big of a deal.

Nag screen may be nice, but I think it's more suited for an upstream change, I'd rather not make that invasive of a change.

**Comment by thelamer** [comment]
We could make it universal and simple. Like if this file exists in /config start the real web service if not start the nag screen service. Have the run command sleep in a loop until that file exists. Then the nag "service" be an extremely simple web app that only writes a file when the button is clicked. Want an example ?

Could be useful for other forms of notifications, most users aren't reading logs or checking readmes.

**Comment by thelamer** [comment]
Yeah python is pretty universal from an image base standpoint and has the least deps. I'll whip up an example regardless, but just in general if you have a dev that is already not fond of people packing up their stuff the sed approach can be easily messed with.

**Comment by thelamer** [comment]
@aptalca here is an example nag screen can be run with `/path/to/nag.py 8000 "The Message you want to display"`
```
#!/usr/bin/env python
import http.server
import os.path
import socketserver
import sys

PORT = int(sys.argv[1])
MESSAGE = sys.argv[2]

# Check if lockfile exists if not run logic
if os.path.exists('/config/.naglock'):
  exit()

# Landing page
html = f"""
  <html>
    <head>
    </head>
    <body>
      <h1>{MESSAGE}</h1>
      <form id="form" action="/" method="POST">
        <input type="submit" value="I Understand">
      </form>
    </body>
  </html>
"""

# After nag
postHtml = """
  <html>
    <head>
    </head>
    <body>
      <h1>Thanks! loading app in 10 seconds</h1>
      <script>
        async function run() {
          await new Promise(resolve => setTimeout(resolve, 10000));
          window.location.href = window.location.href;
        }
        window.onload = run;
      </script>
    </body>
  </html>
"""

# Main server logic
class logic(http.server.SimpleHTTPRequestHandler):
  # Send our html
  def do_GET(self):
    self.send_response(200)
    self.send_header("Content-type", "text/html")
    self.end_headers()
    self.wfile.write(bytes(html, "utf8"))
    return
  # Translate any post as an acceptance of nag
  def do_POST(self):
    self.send_response(200)
    self.send_header("Content-type", "text/html")
    self.end_headers()
    self.wfile.write(bytes(postHtml, "utf8"))
    lock = open('/config/.naglock', 'w')
    lock.write('')
    lock.close()
    server.server_close()
    exit()

# Modify socket server to force ports to close
class socketServer(socketserver.TCPServer):
  def server_bind(self):
    import socket
    self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    self.socket.bind(self.server_address)

serverLogic = logic
server = socketServer(("", PORT), serverLogic)
server.serve_forever()
```

You can simply exec this in the run command (as abc) for the app before the actual daemon is started, if the user has accepted the terms it will never show again, but until they do accept it will always show this nag.

**Pull request closed without merging**
